language: node_js
node_js:
- '11.6'
branches:
  only:
  - master
before_script:
- npm install
deploy:
  provider: npm
  email: helvio88@gmail.com
  api_key:
    secure: E2gnlVpWo7Y1zfwsaOtwMYFQ+917eg9aDdT5oub+v5lp3K2D58gPaIFvqMeirchscTFHIKLsq1cBi6YcqaZdqb6eWg8LrNm5HUKOTpMXXgOnc4dcVqDi6WAGRfsXBVPqyC71wiomsKcWCeAQgloVLwdOcx7set74heorqy0UbO4USTcKGY9A3rMe2563WDwCR3HknZqd3p26mcmCeAMe21MZ0kv1RcJua/NbJIs+FDz603zjZupGE1B6dAxiGSkTvg+TI2VNiFdQiJOOtT0aR236suCEmCJ3j1fNRfnSLrksXCPRwCmLJkXlYsNLH+HdPj4ilFe1EgjexPOm6seGqWuIQ9FN+ahlaQnTIUpWIqttG+MHtPWjVICazHMTzLAyswlGBQukEWdVyRneLki4ZnnTWaOpJBaCKDwcdE+36cERxDRmzn5JNs0ZVEr74zrQDzKuXa5qRhVGju56jRl3RS9RdQD6E8uOhbhWFDGn69KajnyDPIftAPs8KH/y1rOecuJYUE9cI+z2C8EzJMWVqVHuAUMauu7VtVABtVn1XgLWfsbYAsFuoU3S+3dZ2hM8XQX8vQ9zDgM27uou9979p/p3H9mlX8gifr+HWQUNneJP9DkVndOI6Jvd3NNUogXNaXnwRn8fR5izQ4iM1yA8+Akz6FXoOf4sfzNJgvwoOz4=
  on:
    tags: true
    repo: Helvio88/web-screenshot
script:
- node screenshot.js -u https://google.com -x 700 -y 190 -w 300 -h 115 -o google_logo.png
notifications:
  email:
    on_failure: change
    on_success: change
