language: node_js
node_js:
  - "11.6"

branches:
  only:
    - master

before_script:
  - npm install

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $API_KEY
  on:
    tags: true

script:
  - node screenshot.js -u https://google.com -x 700 -y 190 -w 300 -h 115 -o google_logo.png

notifications:
  email:
    on_failure: change
    on_success: change
